
###############################################################################
#
# Inclusive Makefile for the dhcpra_vpi module.
#
# Autogenerated 2014-01-24 17:02:56.013178
#
###############################################################################
dhcpra_vpi_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

