
##############################################################################
#
# Builder Module Manifest.
#
# Autogenerated 2013-11-19 17:21:59.766355
#
##############################################################################
BASEDIR := $(dir $(lastword $(MAKEFILE_LIST)))
lacpa_BASEDIR := $(BASEDIR)lacpa
lldpa_BASEDIR := $(BASEDIR)lldpa


ALL_MODULES := $(ALL_MODULES) lacpa lldpa
