
##############################################################################
#
# Builder Module Manifest.
#
# Autogenerated 2014-10-29 10:38:11.851611
#
##############################################################################
BASEDIR := $(dir $(lastword $(MAKEFILE_LIST)))
arpa_BASEDIR := $(BASEDIR)arpa
arpra_BASEDIR := $(BASEDIR)arpra
cdpa_BASEDIR := $(BASEDIR)cdpa
dhcpra_BASEDIR := $(BASEDIR)dhcpra
icmpa_BASEDIR := $(BASEDIR)icmpa
lacpa_BASEDIR := $(BASEDIR)lacpa
lldpa_BASEDIR := $(BASEDIR)lldpa
router_ip_table_BASEDIR := $(BASEDIR)router_ip_table
sflowa_BASEDIR := $(BASEDIR)sflowa
slshared_BASEDIR := $(BASEDIR)slshared


ALL_MODULES := $(ALL_MODULES) arpa arpra cdpa dhcpra icmpa lacpa lldpa router_ip_table sflowa slshared
