
##############################################################################
#
# Builder Module Manifest.
#
# Autogenerated 2014-10-02 17:55:10.083390
#
##############################################################################
BASEDIR := $(dir $(lastword $(MAKEFILE_LIST)))
arpa_BASEDIR := $(BASEDIR)arpa
arpra_BASEDIR := $(BASEDIR)arpra
dhcpra_BASEDIR := $(BASEDIR)dhcpra
icmpa_BASEDIR := $(BASEDIR)icmpa
lacpa_BASEDIR := $(BASEDIR)lacpa
lldpa_BASEDIR := $(BASEDIR)lldpa
router_ip_table_BASEDIR := $(BASEDIR)router_ip_table
sflowa_BASEDIR := $(BASEDIR)sflowa


ALL_MODULES := $(ALL_MODULES) arpa arpra dhcpra icmpa lacpa lldpa router_ip_table sflowa
