
###############################################################################
#
# Inclusive Makefile for the slshared module.
#
# Autogenerated 2014-10-29 11:19:27.889390
#
###############################################################################
slshared_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(slshared_BASEDIR)/module/make.mk
include $(slshared_BASEDIR)/module/auto/make.mk

