###############################################################################
#
# Local source generation targets.
#
###############################################################################
include ../../../../init.mk
.DEFAULT_GOAL := ucli

ucli:
	@$(SUBMODULE_BIGCODE)/tools/uclihandlers.py arpra_ucli.c

