
###############################################################################
#
# Inclusive Makefile for the sflowa module.
#
# Autogenerated 2014-10-02 17:55:09.816899
#
###############################################################################
sflowa_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(sflowa_BASEDIR)/module/make.mk
include $(sflowa_BASEDIR)/module/src/make.mk
include $(sflowa_BASEDIR)/module/auto/make.mk
include $(sflowa_BASEDIR)/utest/_make.mk

