
###############################################################################
#
# Inclusive Makefile for the lacpa module.
#
# Autogenerated 2013-11-20 16:31:07.175766
#
###############################################################################
lacpa_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(lacpa_BASEDIR)/module/make.mk
include $(lacpa_BASEDIR)/module/auto/make.mk
include $(lacpa_BASEDIR)/module/src/make.mk
include $(lacpa_BASEDIR)/utest/_make.mk

