
###############################################################################
#
# Inclusive Makefile for the arpra module.
#
# Autogenerated 2014-04-21 12:54:50.820553
#
###############################################################################
arpra_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(arpra_BASEDIR)/module/make.mk
include $(arpra_BASEDIR)/module/auto/make.mk
include $(arpra_BASEDIR)/module/src/make.mk
include $(arpra_BASEDIR)/utest/_make.mk

