/**************************************************************************//**
 *
 *
 *
 *****************************************************************************/
#include <sflowa/sflowa_config.h>

#if SFLOWA_CONFIG_INCLUDE_UCLI == 1

#include <uCli/ucli.h>
#include <uCli/ucli_argparse.h>
#include <uCli/ucli_handler_macros.h>

static ucli_status_t
sflowa_ucli_ucli__config__(ucli_context_t* uc)
{
    UCLI_HANDLER_MACRO_MODULE_CONFIG(sflowa)
}

/* <auto.ucli.handlers.start> */
/******************************************************************************
 *
 * These handler table(s) were autogenerated from the symbols in this
 * source file.
 *
 *****************************************************************************/
static ucli_command_handler_f sflowa_ucli_ucli_handlers__[] = 
{
    sflowa_ucli_ucli__config__,
    NULL
};
/******************************************************************************/
/* <auto.ucli.handlers.end> */

static ucli_module_t
sflowa_ucli_module__ =
    {
        "sflowa_ucli",
        NULL,
        sflowa_ucli_ucli_handlers__,
        NULL,
        NULL,
    };

ucli_node_t*
sflowa_ucli_node_create(void)
{
    ucli_node_t* n;
    ucli_module_init(&sflowa_ucli_module__);
    n = ucli_node_create("sflowa", NULL, &sflowa_ucli_module__);
    ucli_node_subnode_add(n, ucli_module_log_node_create("sflowa"));
    return n;
}

#else
void*
sflowa_ucli_node_create(void)
{
    return NULL;
}
#endif

