
###############################################################################
#
# Inclusive Makefile for the lldpa module.
#
# Autogenerated 2013-11-20 16:31:07.455577
#
###############################################################################
lldpa_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(lldpa_BASEDIR)/module/make.mk
include $(lldpa_BASEDIR)/module/auto/make.mk
include $(lldpa_BASEDIR)/module/src/make.mk
include $(lldpa_BASEDIR)/utest/_make.mk

