
###############################################################################
#
# Inclusive Makefile for the arpa module.
#
# Autogenerated 2014-01-10 12:48:30.720554
#
###############################################################################
arpa_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(arpa_BASEDIR)/module/make.mk
include $(arpa_BASEDIR)/module/auto/make.mk
include $(arpa_BASEDIR)/module/src/make.mk
include $(arpa_BASEDIR)/utest/_make.mk

