
###############################################################################
#
# Inclusive Makefile for the cdpa module.
#
# Autogenerated 2014-10-22 13:43:17.008261
#
###############################################################################
cdpa_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(cdpa_BASEDIR)/module/make.mk
include $(cdpa_BASEDIR)/module/src/make.mk
include $(cdpa_BASEDIR)/module/auto/make.mk
include $(cdpa_BASEDIR)/utest/_make.mk

