###############################################################################
#
# 
#
###############################################################################
include ../../init.mk
MODULE := router_ip_table
AUTOMODULE := router_ip_table
include $(BUILDER)/definemodule.mk
