
###############################################################################
#
# Inclusive Makefile for the router_ip_table module.
#
# Autogenerated 2014-01-13 13:12:08.431030
#
###############################################################################
router_ip_table_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(router_ip_table_BASEDIR)/module/make.mk
include $(router_ip_table_BASEDIR)/module/auto/make.mk
include $(router_ip_table_BASEDIR)/module/src/make.mk
include $(router_ip_table_BASEDIR)/utest/_make.mk

