###############################################################################
#
# Local source generation targets.
#
###############################################################################

ucli:
	@$(SUBMODULE_BIGCODE)/tools/uclihandlers.py router_ip_table_ucli.c

