###############################################################################
#
# Local source generation targets.
#
###############################################################################

ucli:
	@$(SUBMODULE_BIGCODE)/tools/uclihandlers.py arpa_ucli.c

